### PR TITLE
Initial Commit: Add PIP Template

### PR DESCRIPTION
**Pull request by ipfs-africa**
Add a suggested template outlining various aspects of the PIP including:

- **Abstract**
- **Specification & Rationale**
- **Backwards Compatibility**
- **Test Cases & Implementation**

This template is heavily influenced by the LUKSO LIPs

### CODE REVIEW

**Review by realChainLife — CHANGES_REQUESTED** [review]
Edit our template as outlined in the PR

**Review by realChainLife — CHANGES_REQUESTED** [review]
Edit out redundant descriptions and comments

**Comment by ipfs-africa** [comment]
New commit modifying the descriptions and comments as recommended.

**Review by realChainLife — CHANGES_REQUESTED** [review]
Add `This template is heavily influenced by the LUKSO LIPs` in the copyright segment and close out

**Comment by ipfs-africa** [comment]
> Add `This template is heavily influenced by the LUKSO LIPs` in the copyright segment and close out

Completed in the latest commit

**Review by realChainLife — APPROVED** [review]

**Pull request merged**
